name: WikiSource Exporter

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Page title (e.g. Constitution_of_the_United_States_of_America)'
        required: true
      lang:
        description: 'Language code: ru, en, de, fr, ...'
        default: 'en'
      format:
        description: 'Output format: txt, epub, pdf'
        default: 'txt'

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: WikiSource Exporter
        uses: ruslanbay/wikisource-exporter@3.1.0
        with:
          title: ${{ github.event.inputs.title }}
          lang: ${{ github.event.inputs.lang }}
          format: ${{ github.event.inputs.format }}
          nocredits: true
          nocache: false
